# Experiments

## Generate samples

In [1]:
from mini_project.algorithms.counter_matrix import L2Estimator, L1Estimator
from mini_project.utils import check_error
import numpy as np
import pandas as pd


def test_l2(test_file,n,N,is_dependent,A,B):
    estimator = L2Estimator(A, B)
    (res, answer, error) = check_error(estimator, test_file,"l2")
    print("error:", error)
    with open('results/counter_matrix_l2_random.csv', 'a') as f:
        f.write(f"{n},{N},{is_dependent},{A},{B},{res},{answer},{error}\n")

df = pd.read_csv("results/counter_matrix_l2_random.csv")


        
n = 10000
N = 1000000
        
A_range = 2 ** np.arange(5)[1:]
B_range = 4 ** np.arange(5)

print(A_range,A_range.shape)
print(B_range,B_range.shape)


for is_dependent in['dependent','independent']:
    test_file = f"{n}-{N}-{is_dependent}-radom"
    print(test_file)
    for A in A_range:
        for B in B_range:
            if len(df[(df['A'] == A) & (df['B'] == B)& (df['is_independent']==is_dependent)])>=1:
                print(f"Skip A={A}, B={B}")
            else:
                print("l2",test_file,n,N,is_dependent,A,B)
                test_l2(test_file,n,N,is_dependent,A,B)



[ 2  4  8 16] (4,)
[  1   4  16  64 256] (5,)
10000-1000000-dependent-radom
Skip A=2, B=1
Skip A=2, B=4
Skip A=2, B=16
Skip A=2, B=64
Skip A=2, B=256
Skip A=4, B=1
Skip A=4, B=4
Skip A=4, B=16
Skip A=4, B=64
Skip A=4, B=256
Skip A=8, B=1
Skip A=8, B=4
Skip A=8, B=16
Skip A=8, B=64
Skip A=8, B=256
Skip A=16, B=1
Skip A=16, B=4
Skip A=16, B=16
Skip A=16, B=64
Skip A=16, B=256
10000-1000000-independent-radom
l2 10000-1000000-independent-radom 10000 1000000 independent 2 1
variance: 0.0
Estimator result: 0.00038079331599999433
Answer: 0.000999886492398402
error: 0.6191634561573132
l2 10000-1000000-independent-radom 10000 1000000 independent 2 4
variance: 3.2743474951437622e-12
Estimator result: 0.0009819185892653726
Answer: 0.000999886492398402
error: 0.017969942858144017
l2 10000-1000000-independent-radom 10000 1000000 independent 2 16
variance: 3.3338104614600946e-13
Estimator result: 0.0006838803050938506
Answer: 0.000999886492398402
error: 0.3160420604808407
l2 10000-1000000-independen

In [ ]:
df = pd.read_csv("results/counter_matrix_l2_random.csv")

A_range = 2 ** np.arange(7)[1:]
B_range = 4 ** np.arange(6)

print(A_range,A_range.shape)
print(B_range,B_range.shape)


for is_dependent in['dependent','independent']:
    test_file = f"{n}-{N}-{is_dependent}-radom"
    print(test_file)
    for A in A_range:
        for B in B_range:
            if len(df[(df['A'] == A) & (df['B'] == B)& (df['is_independent']==is_dependent)])>=1:
                print(f"Skip A={A}, B={B}")
            else:
                print("l2",test_file,n,N,is_dependent,A,B)
                test_l2(test_file,n,N,is_dependent,A,B)

[ 2  4  8 16 32 64] (6,)
[   1    4   16   64  256 1024] (6,)
10000-1000000-dependent-radom
Skip A=2, B=1
Skip A=2, B=4
Skip A=2, B=16
Skip A=2, B=64
Skip A=2, B=256
Skip A=2, B=1024
Skip A=4, B=1
Skip A=4, B=4
Skip A=4, B=16
Skip A=4, B=64
Skip A=4, B=256
Skip A=4, B=1024
Skip A=8, B=1
Skip A=8, B=4
Skip A=8, B=16
Skip A=8, B=64
Skip A=8, B=256
l2 10000-1000000-dependent-radom 10000 1000000 dependent 8 1024


In [ ]:
df = pd.read_csv("results/counter_matrix_l2_random.csv")

A_range = 2 ** np.arange(7)[1:]
B_range = 4 ** np.arange(7)

print(A_range,A_range.shape)
print(B_range,B_range.shape)


for is_dependent in['dependent','independent']:
    test_file = f"{n}-{N}-{is_dependent}-radom"
    print(test_file)
    for A in A_range:
        for B in B_range:
            if len(df[(df['A'] == A) & (df['B'] == B)])>=1:
                print(f"Skip A={A}, B={B}")
            else:
                print("l2",test_file,n,N,is_dependent,A,B)
                test_l2(test_file,n,N,is_dependent,A,B)

In [ ]:
df = pd.read_csv("results/counter_matrix_l2_random.csv")

A_range = 2 ** np.arange(8)[1:]
B_range = 4 ** np.arange(7)

print(A_range,A_range.shape)
print(B_range,B_range.shape)


for is_dependent in['dependent','independent']:
    test_file = f"{n}-{N}-{is_dependent}-radom"
    print(test_file)
    for A in A_range:
        for B in B_range:
            if len(df[(df['A'] == A) & (df['B'] == B)& (df['is_independent']==is_dependent)])>=1:
                print(f"Skip A={A}, B={B}")
            else:
                print("l2",test_file,n,N,is_dependent,A,B)
                test_l2(test_file,n,N,is_dependent,A,B)